;1、域名组
ruleset=🍉 bing,https://raw.githubusercontent.com/waniks/oc-rule/refs/heads/master/list_wa/bing.list
ruleset=🍉 GBF,https://raw.githubusercontent.com/waniks/oc-rule/refs/heads/master/list_wa/GBF.list
ruleset=🍉 NX,https://raw.githubusercontent.com/waniks/oc-rule/refs/heads/master/list_wa/Nexon.list
ruleset=🍉 Steam,https://raw.githubusercontent.com/waniks/oc-rule/refs/heads/master/list_wa/Steam.list
ruleset=🍉 Synology,https://raw.githubusercontent.com/waniks/oc-rule/refs/heads/master/list_wa/Synology.list
ruleset=🍉 UltraMobile,https://raw.githubusercontent.com/waniks/oc-rule/refs/heads/master/list_wa/ultramobile.list
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list
ruleset=✨ Meta AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/MetaAi.list
ruleset=✨ Perplexity,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Perplexity.list
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=🪂 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🙋 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🕊️ Twitter(X),https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=💁 WhatsApp,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list
ruleset=🗣️ Facebook,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list
ruleset=🌳 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🎞️ YouTube,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/YouTube.list
ruleset=🎞️ YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📺 Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎬 HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=👌 虚拟币,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OKX/OKX.list
ruleset=👌 虚拟币,https://raw.githubusercontent.com/v2fly/domain-list-community/refs/heads/master/data/bybit
ruleset=👌 虚拟币,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/xnb.list
ruleset=⏱️ 检测,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=🚅 直连`select`[]DIRECT
custom_proxy_group=🚀 默认代理`select`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🍉 bing`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]新加坡-自动
custom_proxy_group=🍉 GBF`select`[]🚅 直连`[]🚀 默认代理`[]游戏-手动
custom_proxy_group=🍉 NX`select`[]🚅 直连`[]🚀 默认代理`[]游戏-手动`[]美国-自动`[]韩国-自动
custom_proxy_group=🍉 Steam`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]美国-自动
custom_proxy_group=🍉 Synology`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]美国-自动
custom_proxy_group=🍉 UltraMobile`select`[]🚅 直连`[]🚀 默认代理`[]美国-自动
custom_proxy_group=✨ AI`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=✨ Meta AI`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=✨ Perplexity`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=📘 GitHub`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🪂 TikTok`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🙋 Telegram`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🕊️ Twitter(X)`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=💁 WhatsApp`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🗣️ Facebook`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🌳 Amazon`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🍎 Apple`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=Ⓜ️ Microsoft`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🔍 Google`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🎮 Steam`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🕹️ Game`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🎞️ YouTube`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=📺 Disney`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🎥 Netflix`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🎬 HBO`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🎵 Spotify`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=👌 虚拟币`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=⏱️ 检测`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=🌍 国外`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动
custom_proxy_group=➡️ 国内`select`[]🚅 直连`[]🚀 默认代理`[]香港-自动`[]日本-自动`[]新加坡-自动`[]美国-自动`[]韩国-自动`[]香港-手动`[]日本-手动`[]新加坡-手动`[]美国-手动`[]韩国-手动

;3、节点组
custom_proxy_group=游戏-手动`select`游戏`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=香港-自动`url-test`(^(?!游戏)(?!teemo_).*(广港|香港|HK|Hong Kong|🇭🇰|HongKong).*)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=日本-自动`url-test`(^(?!游戏)(?!teemo_).*(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan).*)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=新加坡-自动`url-test`(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=美国-自动`url-test`(广美|美|US|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|🇺🇸|United States)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=韩国-自动`url-test`(广韩|韩国|KR|首尔|春川|🇰🇷|Korea)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=香港-手动`select`(^(?!游戏)(?!teemo_).*(广港|香港|HK|Hong Kong|🇭🇰|HongKong).*)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=日本-手动`select`(^(?!游戏)(?!teemo_).*(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan).*)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=新加坡-手动`select`(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=美国-手动`select`(广美|美|US|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|🇺🇸|United States)`http://cp.cloudflare.com/generate_204`300,5,100
custom_proxy_group=韩国-手动`select`(广韩|韩国|KR|首尔|春川|🇰🇷|Korea)`http://cp.cloudflare.com/generate_204`300,5,100

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
